# Generated by Django 4.0.1 on 2022-01-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas_Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo_despesa', models.CharField(choices=[('f', 'finaciamento'), ('c', 'conta'), ('r', 'reparo'), ('o', 'outro')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('vencimento_fatura', models.DateField()),
                ('status_pagamento', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('n', 'Neutro'), ('o', 'Outro'), ('0', 'Prefiro não dizer')], max_length=1)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indentificacao', models.CharField(max_length=50)),
                ('condominio', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to='main.inquilinos')),
            ],
        ),
    ]
