# Generated by Django 4.0.1 on 2022-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas_unidades',
            name='tipo_despesa',
            field=models.CharField(choices=[('f', 'finaciamento'), ('c', 'conta'), ('r', 'reparo'), ('o', 'outro')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='inquilinos',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('n', 'Neutro'), ('o', 'Outro'), ('0', 'Prefiro não dizer')], default='0', max_length=1),
        ),
    ]
