# Generated by Django 4.0.1 on 2022-01-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_inquilinos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas_unidades',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidade', to='main.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquilinos',
            name='id',
            field=models.CharField(default='351rff0655sb30xc0uy4177g85v5d259905ugagc1q252o07qgc16dk43011myt6', editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
