# Generated by Django 4.0.1 on 2022-01-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_despesas_unidades_unidade_alter_inquilinos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilinos',
            name='id',
            field=models.CharField(default='bjc10l837754ok0050x9rcy443m364nm89wr2908ocm26x21x2371677sfx637l5', editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
